apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-corp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergo-corp
  template:
    metadata:
      labels:
        app: abstergo-corp
    spec:
      containers:
        - name: abstergo-corp-container
          image: saktiranjan/abstergo-corp:latest
          ports:
            - containerPort: 8080

