apiVersion: v1
kind: Service
metadata:
    name: abstergo-corp-svc
spec:
    type: NodePort
    selector:
        app: abstergo-corp
    ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
