apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-corp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergo-corp
  template:
    metadata:
      labels:
        app: abstergo-corp
    spec:
      containers:
        - name: abstergo-corp-container
          image: saktiranjan/abstergo-corp:latest
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
    name: abstergo-corp-svc
spec:
    type: NodePort
    selector:
        app: abstergo-corp
    ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080

